version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8182:80"
    volumes:
      - ./src:/var/www/html  
      - ./uploads:/var/www/html/uploads
      - /mnt/stuworking:/mnt/stuworking
    environment:
      - MAIL_TO=stukerr@hotmail.com
